#!/bin/bash
set -e 
set -x

export ROOT=$PWD
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/JamesClonk/s3-simple-resource

export GOPATH=$PWD/Godeps/_workspace:$GOPATH
export PATH=$PWD/Godeps/_workspace/bin:$PATH

go install github.com/minio/minio-go

make

cd ..
cp -a s3-simple-resource $ROOT
